// // menu Toggle
// let menuOpen = false;
// let menu = document.getElementById("b-menu").addEventListener('click', function () {
//     let mobMenu = document.getElementById("sidebar__mobile");
//     if(!menuOpen){
//         console.log("opening");
//         mobMenu.style.display = "block";
//         menuOpen = true;
//     }else{
//         console.log("closing");
//         // mobMenu.animate({right:})
//         mobMenu.style.display = "none";
//         menuOpen = false;
//     }
// });

// let menuOpen = true;
// let $mobMenu = $("sidebar__mobile");

// let $menu = $("b-menu").on('click', () => {
//     if(!menuOpen){
//         menuOpen = true;
//         $mobMenu.css({"display":"none}"});
//     }else{
//         menuOpen = false;
//         $mobMenu.css({"display":"none}"});
//     }
// });

